using System.Collections.Concurrent;
using System.Net;
using Beholder.Core;
using Microsoft.Diagnostics.Tracing;
using Microsoft.Diagnostics.Tracing.Session;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Beholder.Daemon.Windows;

/// <summary>
/// <see cref="IDnsCache"/> implementation that subscribes to the Microsoft-Windows-DNS-Client
/// ETW provider and maintains an in-memory reverse map of IP address → most recently
/// queried hostname. Runs as an <see cref="IHostedService"/> so the host drives the
/// session lifecycle; the cache populates passively as other processes resolve names,
/// with zero outbound DNS traffic generated by Beholder itself.
/// </summary>
public sealed class EtwDnsCache : IDnsCache, IHostedService, IAsyncDisposable, IDisposable {
    private const string SessionName = "Beholder-DnsTrace";
    private static readonly Guid DnsClientProviderGuid = new("1C95126E-7EEA-49A9-A3FE-A378B03DDB4D");

    // Candidate payload field names across Windows DNS Client ETW event
    // variants. 3008 (DnsQueryCompleted) uses QueryName + QueryResults. 3010
    // (cache lookup) and 3020 (DnsQueryCompletedEx on Win11+) use the same
    // names on current builds, but earlier builds / variant events have used
    // QueryString / Answer / CachedAddresses. We probe each in order and
    // accept the first match, which makes us forward-compatible with minor
    // schema drift without chasing specific event IDs.
    private static readonly string[] QueryNameFields = ["QueryName", "QueryString"];
    private static readonly string[] QueryResultsFields = ["QueryResults", "Answer", "CachedAddresses"];

    // ETW Source.Process() drains on a background thread. 5 s is well above any
    // observed drain time in practice; long enough to flush buffered events,
    // short enough that a stuck session doesn't block daemon shutdown.
    private static readonly TimeSpan StopTimeout = TimeSpan.FromSeconds(5);

    private readonly ILogger<EtwDnsCache> _logger;
    private readonly ConcurrentDictionary<IPAddress, string> _cache = new();
    private readonly object _lifecycleLock = new();

    private TraceEventSession? _session;
    private Task? _processingTask;
    private bool _disposed;

    public EtwDnsCache(ILogger<EtwDnsCache> logger) {
        ArgumentNullException.ThrowIfNull(logger);
        _logger = logger;
    }

    public string? Resolve(IPAddress address) {
        ArgumentNullException.ThrowIfNull(address);
        return _cache.TryGetValue(address, out var hostname) ? hostname : null;
    }

    public Task StartAsync(CancellationToken cancellationToken) {
        lock (_lifecycleLock) {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (_session is not null) throw new InvalidOperationException("DNS ETW session already started.");

            // Beholder-DnsTrace is a regular manifest-provider session, not the per-machine
            // kernel logger singleton. A crashed daemon leaves the session alive until next
            // reboot unless we stop it ourselves, so do a one-shot orphan sweep on start.
            if (TraceEventSession.GetActiveSessionNames().Contains(SessionName)) {
                using var orphan = new TraceEventSession(SessionName);
                orphan.Stop();
            }

            TraceEventSession session;
            try {
                session = new TraceEventSession(SessionName) { StopOnDispose = true };
            } catch (Exception ex) {
                _logger.LogError(
                    ex,
                    "DNS ETW session creation failed — ensure the daemon is running as Administrator");
                throw;
            }

            try {
                session.EnableProvider(DnsClientProviderGuid, TraceEventLevel.Informational);
                session.Source.Dynamic.All += OnEtwEvent;
                _processingTask = Task.Run(() => session.Source.Process());
                _session = session;
            } catch (Exception ex) {
                // EnableProvider is the path that actually throws
                // UnauthorizedAccessException when the daemon isn't elevated —
                // session construction at line 61 succeeds unelevated on Windows.
                // Emit the admin hint here so the user sees it in the stack
                // trace they'll actually encounter.
                _logger.LogError(
                    ex,
                    "DNS ETW provider enable failed — ensure the daemon is running as Administrator");
                session.Dispose();
                throw;
            }

            _logger.LogInformation(
                "DNS ETW trace session started (accepting any event that carries a query name + answer)");
        }

        return Task.CompletedTask;
    }

    public async Task StopAsync(CancellationToken cancellationToken) {
        TraceEventSession? sessionToStop;
        Task? taskToAwait;
        lock (_lifecycleLock) {
            sessionToStop = _session;
            taskToAwait = _processingTask;
            _session = null;
            _processingTask = null;
        }

        if (sessionToStop is null) return;

        sessionToStop.Source.Dynamic.All -= OnEtwEvent;
        sessionToStop.Stop();

        if (taskToAwait is not null) {
            var completed = await Task.WhenAny(
                taskToAwait,
                Task.Delay(StopTimeout, cancellationToken)).ConfigureAwait(false);
            if (completed != taskToAwait) {
                _logger.LogWarning(
                    "DNS ETW processing task did not complete within 5 seconds of session stop");
            }
        }

        sessionToStop.Dispose();
        _logger.LogInformation("DNS ETW trace session stopped");
    }

    public async ValueTask DisposeAsync() {
        if (_disposed) return;
        _disposed = true;
        // StopAsync is idempotent and safe when never started.
        await StopAsync(CancellationToken.None).ConfigureAwait(false);
        GC.SuppressFinalize(this);
    }

    // Fallback for code paths that still resolve IDisposable (e.g. `using`
    // in a sync context). Microsoft.Extensions.DependencyInjection always
    // prefers IAsyncDisposable when both are implemented, so in the daemon
    // this path is effectively dead. Intentionally does NOT block on
    // StopAsync — that would either reintroduce a banned sync-over-async
    // call or risk deadlock on a captured sync context. Prefer DisposeAsync.
    public void Dispose() {
        if (_disposed) return;
        _disposed = true;
        TraceEventSession? session;
        lock (_lifecycleLock) {
            session = _session;
            _session = null;
            _processingTask = null;
        }
        session?.Dispose();
        GC.SuppressFinalize(this);
    }

    private void OnEtwEvent(TraceEvent data) {
        try {
            // Originally we hard-filtered to event id 3008 (DnsQueryCompleted)
            // only. That misses cache-hit lookups (event 3010) which are the
            // common case on a warm machine — revisiting a domain rarely fires
            // 3008 because Windows serves it from the resolver cache. The
            // payload-field probe below covers 3008, 3010, 3020 (Win11
            // DnsQueryCompletedEx), and any future/variant events that expose
            // the same logical fields.
            var queryName = ReadPayloadString(data, QueryNameFields);
            if (string.IsNullOrWhiteSpace(queryName)) return;

            var queryResults = ReadPayloadString(data, QueryResultsFields);
            if (string.IsNullOrWhiteSpace(queryResults)) return;

            Ingest(queryName, queryResults);
        } catch (Exception ex) {
            // Outer ETW boundary: exceptions propagating back into TraceEvent can tear
            // down the entire trace session and, on some Windows SKUs, leave it in a
            // zombie state that persists until reboot. Log and swallow.
            _logger.LogWarning(ex, "Failed to process DNS ETW event {EventName}", data.EventName);
        }
    }

    /// <summary>
    /// Ingests a decoded (queryName, queryResults) pair into the cache — the
    /// same step <see cref="OnEtwEvent"/> performs once it has successfully
    /// pulled both from the raw ETW payload. Exposed as <c>internal</c> so
    /// tests can drive the cache-population path without constructing a
    /// <c>TraceEvent</c>.
    /// </summary>
    internal void Ingest(string queryName, string queryResults) {
        ArgumentException.ThrowIfNullOrWhiteSpace(queryName);
        ArgumentException.ThrowIfNullOrWhiteSpace(queryResults);
        foreach (var address in ExtractAddresses(queryResults)) {
            _cache[address] = queryName;
        }
    }

    /// <summary>
    /// Probes an ETW event's payload for the first of <paramref name="candidateFields"/>
    /// that returns a non-empty string. Returns <c>null</c> if none of the
    /// candidates resolve. Folds the per-event-id field-name differences
    /// inside <see cref="OnEtwEvent"/> into a single call site.
    /// </summary>
    private static string? ReadPayloadString(TraceEvent data, string[] candidateFields) {
        foreach (var field in candidateFields) {
            if (data.PayloadByName(field) is string value && !string.IsNullOrWhiteSpace(value))
                return value;
        }
        return null;
    }

    // Windows formats QueryResults as a semicolon-separated list. Individual entries
    // are usually bare IPs ("93.184.216.34"), but some Windows builds prepend a
    // "type: <code>" prefix ("type:  1 93.184.216.34"). For CNAME records the entry
    // is a hostname, which we skip. The parser is deliberately lenient: it tries the
    // whole segment first, then falls back to the last whitespace-separated token.
    internal static IEnumerable<IPAddress> ExtractAddresses(string queryResults) {
        var segments = queryResults.Split(
            ';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        foreach (var raw in segments) {
            if (IPAddress.TryParse(raw, out var direct)) {
                yield return direct;
                continue;
            }
            var lastSpace = raw.LastIndexOf(' ');
            if (lastSpace >= 0 && IPAddress.TryParse(raw[(lastSpace + 1)..], out var trailing)) {
                yield return trailing;
            }
        }
    }
}
