using System.Collections.Concurrent;
using System.Net;
using Beholder.Core;
using Microsoft.Diagnostics.Tracing;
using Microsoft.Diagnostics.Tracing.Session;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Beholder.Daemon.Windows;

/// <summary>
/// <see cref="IDnsCache"/> implementation that subscribes to the Microsoft-Windows-DNS-Client
/// ETW provider and maintains an in-memory reverse map of IP address → most recently
/// queried hostname. Runs as an <see cref="IHostedService"/> so the host drives the
/// session lifecycle; the cache populates passively as other processes resolve names,
/// with zero outbound DNS traffic generated by Beholder itself.
/// </summary>
public sealed class EtwDnsCache : IDnsCache, IHostedService, IAsyncDisposable, IDisposable {
    private const string SessionName = "Beholder-DnsTrace";
    private const int DnsQueryCompletedEventId = 3008;
    private static readonly Guid DnsClientProviderGuid = new("1C95126E-7EEA-49A9-A3FE-A378B03DDB4D");

    // ETW Source.Process() drains on a background thread. 5 s is well above any
    // observed drain time in practice; long enough to flush buffered events,
    // short enough that a stuck session doesn't block daemon shutdown.
    private static readonly TimeSpan StopTimeout = TimeSpan.FromSeconds(5);

    private readonly ILogger<EtwDnsCache> _logger;
    private readonly ConcurrentDictionary<IPAddress, string> _cache = new();
    private readonly object _lifecycleLock = new();

    private TraceEventSession? _session;
    private Task? _processingTask;
    private bool _disposed;

    public EtwDnsCache(ILogger<EtwDnsCache> logger) {
        ArgumentNullException.ThrowIfNull(logger);
        _logger = logger;
    }

    public string? Resolve(IPAddress address) {
        ArgumentNullException.ThrowIfNull(address);
        return _cache.TryGetValue(address, out var hostname) ? hostname : null;
    }

    public Task StartAsync(CancellationToken cancellationToken) {
        lock (_lifecycleLock) {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (_session is not null) throw new InvalidOperationException("DNS ETW session already started.");

            // Beholder-DnsTrace is a regular manifest-provider session, not the per-machine
            // kernel logger singleton. A crashed daemon leaves the session alive until next
            // reboot unless we stop it ourselves, so do a one-shot orphan sweep on start.
            if (TraceEventSession.GetActiveSessionNames().Contains(SessionName)) {
                using var orphan = new TraceEventSession(SessionName);
                orphan.Stop();
            }

            TraceEventSession session;
            try {
                session = new TraceEventSession(SessionName) { StopOnDispose = true };
            } catch (Exception ex) {
                _logger.LogError(
                    ex,
                    "DNS ETW session creation failed — ensure the daemon is running as Administrator");
                throw;
            }

            try {
                session.EnableProvider(DnsClientProviderGuid, TraceEventLevel.Informational);
                session.Source.Dynamic.All += OnEtwEvent;
                _processingTask = Task.Run(() => session.Source.Process());
                _session = session;
            } catch {
                session.Dispose();
                throw;
            }

            _logger.LogInformation("DNS ETW trace session started");
        }

        return Task.CompletedTask;
    }

    public async Task StopAsync(CancellationToken cancellationToken) {
        TraceEventSession? sessionToStop;
        Task? taskToAwait;
        lock (_lifecycleLock) {
            sessionToStop = _session;
            taskToAwait = _processingTask;
            _session = null;
            _processingTask = null;
        }

        if (sessionToStop is null) return;

        sessionToStop.Source.Dynamic.All -= OnEtwEvent;
        sessionToStop.Stop();

        if (taskToAwait is not null) {
            var completed = await Task.WhenAny(
                taskToAwait,
                Task.Delay(StopTimeout, cancellationToken)).ConfigureAwait(false);
            if (completed != taskToAwait) {
                _logger.LogWarning(
                    "DNS ETW processing task did not complete within 5 seconds of session stop");
            }
        }

        sessionToStop.Dispose();
        _logger.LogInformation("DNS ETW trace session stopped");
    }

    public async ValueTask DisposeAsync() {
        if (_disposed) return;
        _disposed = true;
        // StopAsync is idempotent and safe when never started.
        await StopAsync(CancellationToken.None).ConfigureAwait(false);
        GC.SuppressFinalize(this);
    }

    // Fallback for code paths that still resolve IDisposable (e.g. `using`
    // in a sync context). Microsoft.Extensions.DependencyInjection always
    // prefers IAsyncDisposable when both are implemented, so in the daemon
    // this path is effectively dead. Intentionally does NOT block on
    // StopAsync — that would either reintroduce a banned sync-over-async
    // call or risk deadlock on a captured sync context. Prefer DisposeAsync.
    public void Dispose() {
        if (_disposed) return;
        _disposed = true;
        TraceEventSession? session;
        lock (_lifecycleLock) {
            session = _session;
            _session = null;
            _processingTask = null;
        }
        session?.Dispose();
        GC.SuppressFinalize(this);
    }

    private void OnEtwEvent(TraceEvent data) {
        try {
            // Phase 2.2 diagnostic: log every DNS-provider event we receive at Debug so
            // the operator can confirm the event ID and payload field names match the
            // current Windows build. Removed in a follow-up pass once event-ID 3008 +
            // QueryName/QueryResults are verified on the target machine.
            _logger.LogDebug(
                "DNS ETW: {EventName} ID={Id} Task={Task} Opcode={Opcode}",
                data.EventName, (int)data.ID, data.TaskName, data.OpcodeName);

            if ((int)data.ID != DnsQueryCompletedEventId) return;

            var queryName = data.PayloadByName("QueryName") as string;
            var queryResults = data.PayloadByName("QueryResults") as string;
            if (string.IsNullOrWhiteSpace(queryName)) return;
            if (string.IsNullOrWhiteSpace(queryResults)) return;

            foreach (var address in ExtractAddresses(queryResults)) {
                _cache[address] = queryName;
            }
        } catch (Exception ex) {
            // Outer ETW boundary: exceptions propagating back into TraceEvent can tear
            // down the entire trace session and, on some Windows SKUs, leave it in a
            // zombie state that persists until reboot. Log and swallow.
            _logger.LogWarning(ex, "Failed to process DNS ETW event {EventName}", data.EventName);
        }
    }

    // Windows formats QueryResults as a semicolon-separated list. Individual entries
    // are usually bare IPs ("93.184.216.34"), but some Windows builds prepend a
    // "type: <code>" prefix ("type:  1 93.184.216.34"). For CNAME records the entry
    // is a hostname, which we skip. The parser is deliberately lenient: it tries the
    // whole segment first, then falls back to the last whitespace-separated token.
    private static IEnumerable<IPAddress> ExtractAddresses(string queryResults) {
        var segments = queryResults.Split(
            ';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        foreach (var raw in segments) {
            if (IPAddress.TryParse(raw, out var direct)) {
                yield return direct;
                continue;
            }
            var lastSpace = raw.LastIndexOf(' ');
            if (lastSpace >= 0 && IPAddress.TryParse(raw[(lastSpace + 1)..], out var trailing)) {
                yield return trailing;
            }
        }
    }
}
