using System.Collections.Concurrent;
using System.Net;
using System.Text;
using System.Threading.Channels;
using Beholder.Core;
using Microsoft.Diagnostics.Tracing;
using Microsoft.Diagnostics.Tracing.Session;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Beholder.Daemon.Windows;

/// <summary>
/// <see cref="IDnsCache"/> implementation that subscribes to the Microsoft-Windows-DNS-Client
/// ETW provider and maintains an in-memory reverse map of IP address → most recently
/// queried hostname. Runs as an <see cref="IHostedService"/> so the host drives the
/// session lifecycle; the cache populates passively as other processes resolve names,
/// with zero outbound DNS traffic generated by Beholder itself.
/// </summary>
/// <remarks>
/// Hot-path decoupling: <see cref="OnEtwEvent"/> runs on the ETW drain thread and
/// must return as fast as possible to avoid the session's kernel-side ring filling
/// up (which would silently drop events — <c>EventsLost</c> in ETW terms). It does
/// the minimum work to pull the query-name + answer pair, then offloads to a
/// bounded <see cref="Channel{T}"/> that a background consumer drains via
/// <see cref="Ingest"/>. This matches the pattern prescribed in <c>PRINCIPLES.md
/// §Daemon Hot Path</c> and the one <c>FlowEventPipeline</c> uses for kernel flow
/// events. Overflow falls back to <c>BoundedChannelFullMode.DropOldest</c>; a
/// 30 s metrics timer logs non-zero drop counts and <c>EventsLost</c> deltas so
/// capture gaps are visible instead of invisible.
/// </remarks>
public sealed class EtwDnsCache : IDnsCache, IHostedService, IAsyncDisposable, IDisposable {
    private const string SessionName = "Beholder-DnsTrace";
    private static readonly Guid DnsClientProviderGuid = new("1C95126E-7EEA-49A9-A3FE-A378B03DDB4D");

    // Candidate payload field names across Windows DNS Client ETW event
    // variants. 3008 (DnsQueryCompleted) uses QueryName + QueryResults. 3018
    // (DnsCacheLookup — the cache-hit event, a.k.a. "warm machine" case) and
    // 3020 (DnsQueryCompletedEx on Win11+) use the same names on current
    // builds, but earlier builds / variant events have used QueryString /
    // Answer / CachedAddresses. We probe each in order and accept the first
    // match, which makes us forward-compatible with minor schema drift
    // without chasing specific event IDs. See
    // https://github.com/repnz/etw-providers-docs/blob/master/Manifests-Win10-18990/Microsoft-Windows-DNS-Client.xml
    // for the authoritative event table.
    private static readonly string[] QueryNameFields = ["QueryName", "QueryString"];
    private static readonly string[] QueryResultsFields = ["QueryResults", "Answer", "CachedAddresses"];

    // ETW Source.Process() drains on a background thread. 5 s is well above any
    // observed drain time in practice; long enough to flush buffered events,
    // short enough that a stuck session doesn't block daemon shutdown.
    private static readonly TimeSpan StopTimeout = TimeSpan.FromSeconds(5);

    // How often the metrics loop polls EventsLost + drop counters. Short enough
    // to make bursts visible; long enough that a quiet daemon logs nothing.
    private static readonly TimeSpan MetricsInterval = TimeSpan.FromSeconds(30);

    private readonly ILogger<EtwDnsCache> _logger;
    private readonly DnsOptions _options;
    private readonly ConcurrentDictionary<IPAddress, string> _cache = new();
    private readonly object _lifecycleLock = new();

    private TraceEventSession? _session;
    private Task? _processingTask;
    private Channel<DnsEventSnapshot>? _queue;
    private Task? _consumerTask;
    private Task? _metricsTask;
    private CancellationTokenSource? _backgroundCts;
    private long _droppedCount;       // Interlocked
    private long _eventsReceived;     // Interlocked; every OnEtwEvent invocation
    private long _eventsIngested;     // Interlocked; every successful TryWrite
    private int _eventsLostBaseline;  // Interlocked; TraceEventSession.EventsLost is int
    private bool _disposed;

    // One-shot schema dump: keyed by (EventId << 8 | Version), value is an
    // unused byte. TryAdd returns true on first sight of a given (id, version)
    // tuple, triggering a structured log of the event's payload shape. Runs
    // at most ~10 times over a daemon lifetime since the DNS Client provider
    // has a fixed event table.
    private readonly ConcurrentDictionary<int, byte> _schemaDumped = new();

    public EtwDnsCache(ILogger<EtwDnsCache> logger, IOptionsMonitor<DnsOptions> options) {
        ArgumentNullException.ThrowIfNull(logger);
        ArgumentNullException.ThrowIfNull(options);
        _logger = logger;
        // Snapshot at construction: channel capacity can't change after
        // CreateBounded, and the ETW session's BufferSizeMB is set at session
        // construction. No hot-reload would be honoured anyway.
        _options = options.CurrentValue;
    }

    public string? Resolve(IPAddress address) {
        ArgumentNullException.ThrowIfNull(address);
        return _cache.TryGetValue(address, out var hostname) ? hostname : null;
    }

    public Task StartAsync(CancellationToken cancellationToken) {
        lock (_lifecycleLock) {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (_session is not null) throw new InvalidOperationException("DNS ETW session already started.");

            // Beholder-DnsTrace is a regular manifest-provider session, not the per-machine
            // kernel logger singleton. A crashed daemon leaves the session alive until next
            // reboot unless we stop it ourselves, so do a one-shot orphan sweep on start.
            if (TraceEventSession.GetActiveSessionNames().Contains(SessionName)) {
                using var orphan = new TraceEventSession(SessionName);
                orphan.Stop();
            }

            TraceEventSession session;
            try {
                session = new TraceEventSession(SessionName) {
                    StopOnDispose = true,
                    // Bigger kernel ring absorbs boot-storm / prefetch spikes
                    // before they can cause EventsLost drops on our end.
                    BufferSizeMB = _options.SessionBufferSizeMB,
                };
            } catch (Exception ex) {
                _logger.LogError(
                    ex,
                    "DNS ETW session creation failed — ensure the daemon is running as Administrator");
                throw;
            }

            try {
                // Explicit keyword mask of -1 (all bits) is defensive: default
                // behaviour is "all keywords at the given level", but
                // providers can in principle ship a non-zero default mask that
                // would gate out events we'd otherwise want.
                session.EnableProvider(
                    DnsClientProviderGuid,
                    TraceEventLevel.Informational,
                    matchAnyKeywords: unchecked((ulong)-1));
                session.Source.Dynamic.All += OnEtwEvent;
                _processingTask = Task.Run(() => session.Source.Process());
                _session = session;
            } catch (Exception ex) {
                // EnableProvider is the path that actually throws
                // UnauthorizedAccessException when the daemon isn't elevated —
                // session construction at line 61 succeeds unelevated on Windows.
                // Emit the admin hint here so the user sees it in the stack
                // trace they'll actually encounter.
                _logger.LogError(
                    ex,
                    "DNS ETW provider enable failed — ensure the daemon is running as Administrator");
                session.Dispose();
                throw;
            }

            // DropOldest semantics: under overflow, the oldest queued event is
            // evicted to make room. TryWrite always returns true in this mode
            // — drops are signalled via the ItemDropped callback instead,
            // which fires for each evicted entry.
            _queue = Channel.CreateBounded<DnsEventSnapshot>(
                new BoundedChannelOptions(_options.QueueCapacity) {
                    FullMode = BoundedChannelFullMode.DropOldest,
                    SingleReader = true,
                    SingleWriter = true,
                },
                itemDropped: OnItemDropped);

            // Preload BEFORE the consumer starts so IngestResolved writes go
            // directly into _cache (which is thread-safe); the ordering also
            // means any very-early ETW event that arrives on the drain thread
            // finds a populated cache and won't overwrite a fresh resolution
            // with a stale preload value. Synchronous on purpose — preload
            // completes in single-digit ms on a typical warm machine.
            PreloadFromWindowsDnsCache();

            _backgroundCts = new CancellationTokenSource();
            // Pass the channel as a captured local rather than letting the
            // consumer re-read _queue at start — StopAsync nulls _queue
            // before awaiting the consumer task, and under thread-pool
            // pressure the consumer can start AFTER that nulling and see a
            // null _queue, silently skipping the drain. Captured local keeps
            // the consumer's view stable across the lifecycle transition.
            var queueForConsumer = _queue;
            var ctsForConsumer = _backgroundCts;
            _consumerTask = Task.Run(() => ConsumeAsync(queueForConsumer, ctsForConsumer.Token));
            _metricsTask = Task.Run(() => RunMetricsLoopAsync(_backgroundCts.Token));

            _logger.LogInformation(
                "DNS ETW trace session started (session buffer {SessionBufferSizeMB} MB, queue capacity {QueueCapacity})",
                _options.SessionBufferSizeMB,
                _options.QueueCapacity);
        }

        return Task.CompletedTask;
    }

    public async Task StopAsync(CancellationToken cancellationToken) {
        TraceEventSession? sessionToStop;
        Task? processingTaskToAwait;
        Channel<DnsEventSnapshot>? queueToComplete;
        Task? consumerTaskToAwait;
        Task? metricsTaskToAwait;
        CancellationTokenSource? ctsToCancel;
        lock (_lifecycleLock) {
            sessionToStop = _session;
            processingTaskToAwait = _processingTask;
            queueToComplete = _queue;
            consumerTaskToAwait = _consumerTask;
            metricsTaskToAwait = _metricsTask;
            ctsToCancel = _backgroundCts;
            _session = null;
            _processingTask = null;
            _queue = null;
            _consumerTask = null;
            _metricsTask = null;
            _backgroundCts = null;
        }

        if (sessionToStop is null) return;

        // 1. Stop ETW first — no more events enter the queue.
        sessionToStop.Source.Dynamic.All -= OnEtwEvent;
        sessionToStop.Stop();

        // 2. Complete the writer so the consumer's ReadAllAsync returns cleanly
        //    after draining whatever is already queued. This is the graceful
        //    path that preserves already-observed events.
        queueToComplete?.Writer.TryComplete();

        // 3. Cancel the metrics loop — it's a PeriodicTimer, cancellation is
        //    the only clean way out. (Consumer exits on Writer.Complete above.)
        ctsToCancel?.Cancel();

        if (processingTaskToAwait is not null) {
            var completed = await Task.WhenAny(
                processingTaskToAwait,
                Task.Delay(StopTimeout, cancellationToken)).ConfigureAwait(false);
            if (completed != processingTaskToAwait) {
                _logger.LogWarning(
                    "DNS ETW processing task did not complete within {TimeoutSeconds} seconds of session stop",
                    StopTimeout.TotalSeconds);
            }
        }

        if (consumerTaskToAwait is not null) {
            var completed = await Task.WhenAny(
                consumerTaskToAwait,
                Task.Delay(StopTimeout, cancellationToken)).ConfigureAwait(false);
            if (completed != consumerTaskToAwait) {
                _logger.LogWarning(
                    "DNS cache consumer did not drain within {TimeoutSeconds} seconds of shutdown",
                    StopTimeout.TotalSeconds);
            }
        }

        if (metricsTaskToAwait is not null) {
            // Metrics loop is always responsive to cancellation via PeriodicTimer;
            // no timeout needed but still use WhenAny for consistency.
            await Task.WhenAny(
                metricsTaskToAwait,
                Task.Delay(StopTimeout, cancellationToken)).ConfigureAwait(false);
        }

        ctsToCancel?.Dispose();
        sessionToStop.Dispose();
        _logger.LogInformation("DNS ETW trace session stopped");
    }

    public async ValueTask DisposeAsync() {
        if (_disposed) return;
        _disposed = true;
        // StopAsync is idempotent and safe when never started.
        await StopAsync(CancellationToken.None).ConfigureAwait(false);
        GC.SuppressFinalize(this);
    }

    // Fallback for code paths that still resolve IDisposable (e.g. `using`
    // in a sync context). Microsoft.Extensions.DependencyInjection always
    // prefers IAsyncDisposable when both are implemented, so in the daemon
    // this path is effectively dead. Intentionally does NOT block on
    // StopAsync — that would either reintroduce a banned sync-over-async
    // call or risk deadlock on a captured sync context. Prefer DisposeAsync.
    public void Dispose() {
        if (_disposed) return;
        _disposed = true;
        TraceEventSession? session;
        CancellationTokenSource? cts;
        lock (_lifecycleLock) {
            session = _session;
            cts = _backgroundCts;
            _session = null;
            _processingTask = null;
            _queue = null;
            _consumerTask = null;
            _metricsTask = null;
            _backgroundCts = null;
        }
        cts?.Cancel();
        cts?.Dispose();
        session?.Dispose();
        GC.SuppressFinalize(this);
    }

    private void OnItemDropped(DnsEventSnapshot dropped) {
        // Called synchronously by the Channel when DropOldest evicts an entry
        // to make room. Kept to a single Interlocked increment to stay cheap —
        // this may run on the producer thread (i.e. the ETW drain path).
        Interlocked.Increment(ref _droppedCount);
    }

    private void OnEtwEvent(TraceEvent data) {
        // Hot path: this runs on the ETW drain thread and must return as
        // fast as possible to keep the session's kernel ring from filling.
        // Do only the minimum needed to pull the query-name + answer pair,
        // then enqueue. All parsing + cache updates happen in ConsumeAsync.

        // Diagnostic: count every callback invocation, regardless of whether
        // we recognise the event. The gap between this and _eventsIngested
        // is the payload-probe miss count — the metric that tells us whether
        // Win11 shipped a schema our field probe doesn't handle.
        Interlocked.Increment(ref _eventsReceived);

        // One-shot per-event-id schema dump, so the first sighting of each
        // event variant the provider emits on THIS machine is visible in
        // logs. Runs at most once per (id, version) tuple.
        MaybeDumpSchemaOnce(data);

        try {
            var queryName = ReadPayloadString(data, QueryNameFields);
            if (string.IsNullOrWhiteSpace(queryName)) return;

            var queryResults = ReadPayloadString(data, QueryResultsFields);
            if (string.IsNullOrWhiteSpace(queryResults)) return;

            // TraceEvent is a flyweight — the `data` argument is reused for
            // the next event as soon as this callback returns. Snapshotting
            // via `new DnsEventSnapshot(queryName, queryResults)` copies two
            // string references; the strings themselves are TraceEvent's own
            // per-event allocations and stay alive as long as we hold the
            // ref. DO NOT replace with a `TraceEvent` capture.
            //
            // TryWrite always returns true under DropOldest — we rely on the
            // ItemDropped callback wired at channel-creation time to count
            // overflow events. When it does return true we count the success.
            if (_queue?.Writer.TryWrite(new DnsEventSnapshot(queryName, queryResults)) == true)
                Interlocked.Increment(ref _eventsIngested);
        } catch (Exception ex) {
            // Outer ETW boundary: exceptions propagating back into TraceEvent can tear
            // down the entire trace session and, on some Windows SKUs, leave it in a
            // zombie state that persists until reboot. Log and swallow.
            _logger.LogWarning(ex, "Failed to enqueue DNS ETW event {EventName}", data.EventName);
        }
    }

    private void MaybeDumpSchemaOnce(TraceEvent data) {
        // Key includes version so a provider that ships a v2 variant of an
        // event ID we already saw as v1 still gets a fresh schema dump.
        var key = ((int)data.ID << 8) | (data.Version & 0xFF);
        if (!_schemaDumped.TryAdd(key, 0)) return;

        try {
            var summary = BuildSchemaSummary(data);
            _logger.LogInformation(
                "DNS ETW event first-seen id={EventId} v={Version} name={EventName} fields={Fields}",
                (int)data.ID,
                data.Version,
                data.EventName ?? "(unknown)",
                summary);
        } catch (Exception ex) {
            // Schema introspection failure must not tear down the session —
            // log and move on. The ingest happy path stays intact.
            _logger.LogWarning(
                ex, "Failed to build schema summary for DNS event id={EventId}", (int)data.ID);
        }
    }

    private static string BuildSchemaSummary(TraceEvent data) {
        var sb = new StringBuilder();
        sb.Append('{');
        var names = data.PayloadNames;
        for (var i = 0; i < names.Length; i++) {
            if (i > 0) sb.Append(", ");
            var name = names[i];
            object? value = null;
            try {
                value = data.PayloadValue(i);
            } catch {
                // Best-effort dump — a field that fails to marshal still
                // tells us its name, which is enough to extend the probe.
            }
            var typeName = value?.GetType().Name ?? "null";
            var repr = value switch {
                null => "null",
                string s when s.Length > 80 => "\"" + s[..80] + "…\"",
                string s => "\"" + s + "\"",
                _ => value.ToString() ?? "?",
            };
            sb.Append(name).Append('=').Append(typeName).Append('(').Append(repr).Append(')');
        }
        sb.Append('}');
        return sb.ToString();
    }

    private async Task ConsumeAsync(
        Channel<DnsEventSnapshot> queue,
        CancellationToken cancellationToken
    ) {
        try {
            await foreach (var ev in queue.Reader.ReadAllAsync(cancellationToken)
                                                 .ConfigureAwait(false)) {
                try {
                    Ingest(ev.QueryName, ev.QueryResults);
                } catch (Exception ex) {
                    // Same rationale as the ETW boundary: a bad event must
                    // not kill the consumer loop.
                    _logger.LogWarning(
                        ex,
                        "Failed to ingest DNS event for {QueryName}",
                        ev.QueryName);
                }
            }
        } catch (OperationCanceledException) {
            // Clean shutdown path; Writer.Complete or CTS cancellation.
        }
    }

    private async Task RunMetricsLoopAsync(CancellationToken cancellationToken) {
        using var timer = new PeriodicTimer(MetricsInterval);
        try {
            while (await timer.WaitForNextTickAsync(cancellationToken).ConfigureAwait(false)) {
                LogMetricsIfAny();
            }
        } catch (OperationCanceledException) {
            // Clean shutdown.
        }
    }

    private void LogMetricsIfAny() {
        // Snapshot under the lifecycle lock so a concurrent StopAsync doesn't
        // null-out _session mid-read.
        TraceEventSession? session;
        Channel<DnsEventSnapshot>? queue;
        lock (_lifecycleLock) {
            session = _session;
            queue = _queue;
        }
        if (session is null || queue is null) return;

        var currentEventsLost = session.EventsLost;
        var previousEventsLost = Interlocked.Exchange(ref _eventsLostBaseline, currentEventsLost);
        var eventsLostDelta = currentEventsLost - previousEventsLost;
        if (eventsLostDelta < 0) eventsLostDelta = 0;  // counter reset — treat as zero this window

        // Exchange all per-window counters to zero and capture the deltas for
        // this window. Ordering note: the reads happen close together so a
        // burst arriving mid-read skews a window by at most one tick; for
        // diagnostics that's fine.
        var queueDrops = Interlocked.Exchange(ref _droppedCount, 0);
        var receivedDelta = Interlocked.Exchange(ref _eventsReceived, 0);
        var ingestedDelta = Interlocked.Exchange(ref _eventsIngested, 0);
        var queueDepth = queue.Reader.Count;

        // probe-dropped = events the callback saw but whose QueryName or
        // QueryResults field didn't decode to a string via our probe. The
        // classic diagnostic for Win11 schema drift. Channel drops ARE
        // counted in `ingested` (the successful TryWrite happened) so we
        // subtract them out — the leftover is true probe failure.
        var probeDropped = receivedDelta - ingestedDelta - queueDrops;
        if (probeDropped < 0) probeDropped = 0;  // defensive; shouldn't happen

        // Silent when truly idle — no events seen, no pressure, no backlog.
        if (receivedDelta == 0 && ingestedDelta == 0 && eventsLostDelta == 0
            && queueDrops == 0 && queueDepth == 0) return;

        // Warning when ANY pressure signal fired in this window; Information
        // when we're just reporting healthy activity so troubleshooting
        // sessions can see the system is working.
        var healthy = eventsLostDelta == 0 && queueDrops == 0 && probeDropped == 0;
        var level = healthy ? LogLevel.Information : LogLevel.Warning;
        var status = healthy ? "steady" : "pressure";

        _logger.Log(
            level,
            "DNS capture {Status}: received={Received} ingested={Ingested} probe-dropped={ProbeDropped} ETW-lost={Lost} queue-drops={Drops} depth={Depth}/{Capacity}",
            status,
            receivedDelta,
            ingestedDelta,
            probeDropped,
            eventsLostDelta,
            queueDrops,
            queueDepth,
            _options.QueueCapacity);
    }

    /// <summary>
    /// Ingests a decoded (queryName, queryResults) pair into the cache — the
    /// same step <see cref="ConsumeAsync"/> performs once it has pulled one
    /// off the channel. Exposed as <c>internal</c> so tests can drive the
    /// cache-population path without constructing a <c>TraceEvent</c>.
    /// </summary>
    internal void Ingest(string queryName, string queryResults) {
        ArgumentException.ThrowIfNullOrWhiteSpace(queryName);
        ArgumentException.ThrowIfNullOrWhiteSpace(queryResults);
        foreach (var address in ExtractAddresses(queryResults)) {
            _cache[address] = queryName;
        }
    }

    /// <summary>
    /// Writes a pre-parsed (queryName, address) pair directly into the cache,
    /// bypassing <see cref="ExtractAddresses"/>. Used by the preload path
    /// (<see cref="PreloadFromWindowsDnsCache"/>) where records come from
    /// <c>DnsQuery_W</c> already typed, and by tests that want deterministic
    /// control over cache contents without building a Windows-formatted
    /// answer string. Same last-writer-wins semantics as <see cref="Ingest"/>.
    /// </summary>
    internal void IngestResolved(string queryName, IPAddress address) {
        ArgumentException.ThrowIfNullOrWhiteSpace(queryName);
        ArgumentNullException.ThrowIfNull(address);
        _cache[address] = queryName;
    }

    /// <summary>
    /// One-shot preload: enumerates the Windows DNS resolver cache via
    /// <see cref="DnsApiInterop.TryEnumerateResolverCache"/> and folds each
    /// (name, address) pair into <c>_cache</c>. Runs at the tail of
    /// <see cref="StartAsync"/>, before the ETW consumer starts, to close
    /// the cold-start gap where flows opened before the daemon attached to
    /// ETW would otherwise show as raw IPs indefinitely. Any failure inside
    /// the interop layer is logged there and surfaces here as a zero-element
    /// enumeration — the daemon still starts successfully.
    /// </summary>
    private void PreloadFromWindowsDnsCache() {
        var loaded = 0;
        foreach (var (name, address) in DnsApiInterop.TryEnumerateResolverCache(_logger)) {
            IngestResolved(name, address);
            loaded++;
        }
        if (loaded > 0)
            _logger.LogInformation(
                "Preloaded {Count} entries from Windows DNS resolver cache", loaded);
    }

    /// <summary>
    /// Test-only: pushes a synthetic event onto the queue as if it had been
    /// decoded from an ETW payload. Under <see cref="BoundedChannelFullMode.DropOldest"/>
    /// this always succeeds — overflows are counted via the channel's
    /// ItemDropped callback, exposed through <see cref="DroppedCount"/>.
    /// Returns <c>false</c> only when the queue hasn't been started yet.
    /// </summary>
    internal bool TryEnqueueForTest(string queryName, string queryResults) {
        var queue = _queue;
        if (queue is null) return false;
        return queue.Writer.TryWrite(new DnsEventSnapshot(queryName, queryResults));
    }

    /// <summary>Test-only: current queue drop counter.</summary>
    internal long DroppedCount => Interlocked.Read(ref _droppedCount);

    /// <summary>
    /// Test-only: creates the queue and starts the consumer + metrics loop
    /// WITHOUT opening an ETW session. The real <see cref="StartAsync"/>
    /// requires Administrator and a live DNS Client provider; tests running
    /// under the xUnit runner usually have neither. This helper stands in
    /// for "everything StartAsync does except the kernel-side work", so
    /// channel-level invariants (DropOldest, graceful drain, Resolve
    /// round-trip) are exercisable without elevation.
    /// </summary>
    internal void TestStartQueueOnly() {
        lock (_lifecycleLock) {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (_queue is not null) throw new InvalidOperationException("Queue already started.");

            _queue = Channel.CreateBounded<DnsEventSnapshot>(
                new BoundedChannelOptions(_options.QueueCapacity) {
                    FullMode = BoundedChannelFullMode.DropOldest,
                    SingleReader = true,
                    SingleWriter = true,
                },
                itemDropped: OnItemDropped);
            _backgroundCts = new CancellationTokenSource();
            // Capture locals so the consumer's view is stable across the
            // StopAsync / TestStopQueueOnlyAsync teardown that nulls _queue.
            var queueForConsumer = _queue;
            var ctsForConsumer = _backgroundCts;
            _consumerTask = Task.Run(() => ConsumeAsync(queueForConsumer, ctsForConsumer.Token));
        }
    }

    /// <summary>
    /// Test-only counterpart to <see cref="TestStartQueueOnly"/>: completes
    /// the queue writer, awaits the consumer drain, and disposes the
    /// cancellation source. Mirrors the graceful-drain sequence in
    /// <see cref="StopAsync"/> for the non-ETW half of the component.
    /// </summary>
    internal async Task TestStopQueueOnlyAsync() {
        Channel<DnsEventSnapshot>? queueToComplete;
        Task? consumerTaskToAwait;
        CancellationTokenSource? ctsToCancel;
        lock (_lifecycleLock) {
            queueToComplete = _queue;
            consumerTaskToAwait = _consumerTask;
            ctsToCancel = _backgroundCts;
            _queue = null;
            _consumerTask = null;
            _backgroundCts = null;
        }

        queueToComplete?.Writer.TryComplete();
        if (consumerTaskToAwait is not null) {
            var completed = await Task.WhenAny(
                consumerTaskToAwait,
                Task.Delay(StopTimeout)).ConfigureAwait(false);
            if (completed != consumerTaskToAwait) {
                // Shouldn't happen on the test path; if it does, fail loud.
                throw new TimeoutException(
                    "Test queue consumer did not drain within stop timeout.");
            }
        }
        ctsToCancel?.Cancel();
        ctsToCancel?.Dispose();
    }

    /// <summary>
    /// Probes an ETW event's payload for the first of <paramref name="candidateFields"/>
    /// that returns a non-empty string. Returns <c>null</c> if none of the
    /// candidates resolve. Folds the per-event-id field-name differences
    /// inside <see cref="OnEtwEvent"/> into a single call site.
    /// </summary>
    private static string? ReadPayloadString(TraceEvent data, string[] candidateFields) {
        foreach (var field in candidateFields) {
            if (data.PayloadByName(field) is string value && !string.IsNullOrWhiteSpace(value))
                return value;
        }
        return null;
    }

    // Windows formats QueryResults as a semicolon-separated list. Individual entries
    // are usually bare IPs ("93.184.216.34"), but some Windows builds prepend a
    // "type: <code>" prefix ("type:  1 93.184.216.34"). For CNAME records the entry
    // is a hostname, which we skip. The parser is deliberately lenient: it tries the
    // whole segment first, then falls back to the last whitespace-separated token.
    internal static IEnumerable<IPAddress> ExtractAddresses(string queryResults) {
        var segments = queryResults.Split(
            ';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        foreach (var raw in segments) {
            if (IPAddress.TryParse(raw, out var direct)) {
                yield return direct;
                continue;
            }
            var lastSpace = raw.LastIndexOf(' ');
            if (lastSpace >= 0 && IPAddress.TryParse(raw[(lastSpace + 1)..], out var trailing)) {
                yield return trailing;
            }
        }
    }

    /// <summary>
    /// In-flight snapshot of a decoded ETW event — the two fields
    /// <see cref="OnEtwEvent"/> pulls from the payload before enqueueing.
    /// Record struct so the Channel's internal ring buffer stores values
    /// rather than heap references. Strings inside the struct are TraceEvent's
    /// per-event allocations and stay alive as long as the struct is enqueued.
    /// </summary>
    internal readonly record struct DnsEventSnapshot(string QueryName, string QueryResults);
}
